### ISSUE TITLE
Changelog des emplois du temps.

### ISSUE THREAD

**Issue by alessandrorubio** [DeptInfoProjects/L2_Info#1]
Pourriez-vous fournir un historique des changements par apport a chaque version des emploi de temps?

**Comment by odalle** [comment]
Ca serait effectivement utile, je vais refléchir à une solution qui s'intègre bien avec github.

**Comment by rubi0** [comment]
Peut être un tableau en markdown avec un commit pour chaque version? 🙄

**Comment by rubi0** [comment]
Je me suis permis d'en faire un, voici le [lien](https://github.com/rubi0/L2-Edt/blob/master/emploiDuTemps.md)
